apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - env:
        - name: PORT
          value: '7070'
        - name: REDIS_ADDR
          value: redis-cart:6379
        image: iamfet/cartservice:14542275320
        livenessProbe:
          grpc:
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 5
        name: service
        ports:
        - containerPort: 7070
        readinessProbe:
          grpc:
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 180Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  ports:
  - port: 7070
    targetPort: 7070
  selector:
    app: cartservice
  type: ClusterIP
---
