apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - env:
        - name: PORT
          value: '5050'
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice:50051
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        - name: CART_SERVICE_ADDR
          value: cartservice:7070
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice:7000
        - name: EMAIL_SERVICE_ADDR
          value: emailservice:5000
        - name: PAYMENT_SERVICE_ADDR
          value: paymentservice:50051
        image: iamfet/checkoutservice:14542275320
        livenessProbe:
          grpc:
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 5
        name: service
        ports:
        - containerPort: 5050
        readinessProbe:
          grpc:
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: checkoutservice
  type: ClusterIP
---
