apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - env:
        - name: PORT
          value: '7000'
        - name: DISABLE_PROFILER
          value: '1'
        image: iamfet/currencyservice:14542275320
        livenessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 5
        name: service
        ports:
        - containerPort: 7000
        readinessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  ports:
  - port: 7000
    targetPort: 7000
  selector:
    app: currencyservice
  type: ClusterIP
---
