apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - env:
        - name: PORT
          value: '3550'
        - name: DISABLE_PROFILER
          value: '1'
        image: iamfet/productcatalogservice:14718353262
        livenessProbe:
          grpc:
            port: 3550
          initialDelaySeconds: 5
          periodSeconds: 5
        name: service
        ports:
        - containerPort: 3550
        readinessProbe:
          grpc:
            port: 3550
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  ports:
  - port: 3550
    targetPort: 3550
  selector:
    app: productcatalogservice
  type: ClusterIP
---
